---
title: "HardWork6"
author: "Cortland Watson"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    code_folding: hide
---

```{r, include=FALSE}
library(mosaic)
library(pander)
library(lmtest)
library(car)
library(alr3)
```


<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

<hr />

# Reading {25}
<div style="padding-left:45px;">
| Section  | Points |
|----------|--------|
|8.2       |   7       |      
|   8.3    |    7      |    
|      8.4 |     3     |
|8.5       |   5       |
|8.6       |    3      |

</div>

<hr/>
<br/>

<!-- #########################  Theory   ############################ -->

# Theory {0/4}

<!-- P R O B L E M     B E G I N S --> 

<div style="padding-left:45px;">
## Exercise  8.17 {0/2}

</div>

<div style="padding-left:60px;">
### <a href="javascript:showhide('Problem 8.17')">Problem 8.17</a>

<div id="Problem 8.17" style="display:none;">


</div>
</div>

<div style="padding-left:70px;">
<!-- Type Problem here -->

### Solution
<!-- Type Solution here -->


</div>

<!-- P R O B L E M    E N D S -->



<!-- P R O B L E M     B E G I N S --> 

<div style="padding-left:45px;">
## Exercise 8.21{0/2}
</div>

<div style="padding-left:60px;">
### <a href="javascript:showhide('Problem 8.21')">Problem 8.21</a>

<div id="Problem 8.21" style="display:none;">


</div>
</div>

<div style="padding-left:70px;">
<!-- Type Problem here -->

### Solution
<!-- Type Solution here -->

</div>

<!-- P R O B L E M    E N D S -->


<hr/>
<br/>

<!-- ######################### Application ############################ -->

# Application {0/17}

<!-- P R O B L E M     B E G I N S --> 

<div style="padding-left:45px;">
## Exercise 8.15{0/5}
</div>

<div style="padding-left:60px;">
### <a href="javascript:showhide('Problem 8.15')">Problem 8.15</a>

<div id="Problem 8.15" style="display:none;">

```{r, include=FALSE}
# It has to be merged from the 1.20 and 8.15 data files.
p1.20 <- read.table("http://www.stat.ufl.edu/~rrandles/sta4210/Rclassnotes/data/textdatasets/KutnerData/Chapter%20%201%20Data%20Sets/CH01PR20.txt", header=FALSE)
p8.15 <- read.table("http://www.stat.ufl.edu/~rrandles/sta4210/Rclassnotes/data/textdatasets/KutnerData/Chapter%20%208%20Data%20Sets/CH08PR15.txt", header=FALSE)
p15 <- cbind(p1.20,p8.15)
colnames(p15) <- c("Y","X1","X2")
```

Oh Yeah!

</div>
</div>

<div style="padding-left:70px;">
<!-- Type Problem here -->

### Solution
<!-- Type Solution here -->

</div>

<!-- P R O B L E M    E N D S -->

<!-- P R O B L E M     B E G I N S --> 

<div style="padding-left:45px;">
## Exercise 8.16{0/5}
</div>

<div style="padding-left:60px;">
### <a href="javascript:showhide('Problem 8.16')">Problem 8.16</a>

<div id="Problem 8.16" style="display:none;">

```{r, include=FALSE}
p1.19 <- read.table("http://www.stat.ufl.edu/~rrandles/sta4210/Rclassnotes/data/textdatasets/KutnerData/Chapter%20%201%20Data%20Sets/CH01PR19.txt", header=FALSE)
p8.16 <- read.table("http://www.stat.ufl.edu/~rrandles/sta4210/Rclassnotes/data/textdatasets/KutnerData/Chapter%20%208%20Data%20Sets/CH08PR16.txt", header=FALSE)
p16 <- cbind(p1.19,p8.16)
colnames(p16) <- c("Y","X1","X2")
```

Oh Yeah!

</div>
</div>

<div style="padding-left:70px;">
<!-- Type Problem here -->

### Solution
<!-- Type Solution here -->

</div>

<!-- P R O B L E M    E N D S -->

<!-- P R O B L E M     B E G I N S --> 

<div style="padding-left:45px;">
## Exercise 8.19{0/3}
</div>

<div style="padding-left:60px;">
### <a href="javascript:showhide('Problem 8.19')">Problem 8.19</a>

<div id="Problem 8.19" style="display:none;">

```{r, include=FALSE}
# Use data from above
```

Oh Yeah!

</div>
</div>

<div style="padding-left:70px;">
<!-- Type Problem here -->

### Solution
<!-- Type Solution here -->

</div>

<!-- P R O B L E M    E N D S -->


<!-- P R O B L E M     B E G I N S --> 

<div style="padding-left:45px;">
## Exercise 8.24{0/4}
</div>

<div style="padding-left:60px;">
### <a href="javascript:showhide('Problem 8.24')">Problem 8.24</a>

<div id="Problem 8.24" style="display:none;">

```{r, include=FALSE}
p24 <- read.table("http://www.stat.ufl.edu/~rrandles/sta4210/Rclassnotes/data/textdatasets/KutnerData/Chapter%20%208%20Data%20Sets/CH08PR24.txt", header=FALSE)
colnames(p24) <- c("Y","X1","X2")
```

Oh Yeah!

</div>
</div>

<div style="padding-left:70px;">
<!-- Type Problem here -->

### Solution
<!-- Type Solution here -->

</div>

<!-- P R O B L E M    E N D S -->



</div>